use_frameworks!

platform :ios, '10.0'

target 'ModFavoritos_Example' do
  pod 'ModFavoritos', :path => '../'
#  pod 'SwiftLint'
  pod 'Alamofire', '~> 5.4.1'
  pod 'AlamofireImage', '~> 4.1.0'

  target 'ModFavoritos_Tests' do
    inherit! :search_paths

    
  end
end
